### ISSUE TITLE
Photos Section responsiveness is broken at medium window size

### ISSUE THREAD

**Issue by Geekavenger** [mc-funk/rossconklin-michellefunk#6]
The photos are collapsing as the screen size shrinks but leave some gaps in the grid.  
![image](https://cloud.githubusercontent.com/assets/11590087/13381397/c15e6332-de20-11e5-95a0-20afc501fcc4.png)

**Comment by mc-funk** [comment]
Display at large and small sizes are fine; medium produces empty boxes

**Comment by mc-funk** [comment]
The reason for this problem is not because of the styling, but a result of all the photos not being the exact same height and width. This can be resolved by re-cropping the images to one size, which is a matter of time rather than a technical problem.
